apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: application-service
  labels:
    app: notification-microservice
spec:
  selector:
    app: notification-microservice
  ports:
    - protocol: TCP
      port: 8082         # Exposing port 8080 for backend traffic (example)
      targetPort: 8082    # The container's port
  type: ClusterIP